version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "33006:3306"
    expose:
      # Opens port 3306 on the container
      - "33006"
      # Where our data will be persisted
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d/
    networks:
      - app-net
  app:
    restart: on-failure
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    expose:
      - "9090"
    ports:
      - 9090:9090
    depends_on:
      - db
    networks:
      - app-net
  front:
    container_name: front
    build:
      context: ../
      dockerfile: ./front/Dockerfile
    ports:
      - 3001:3000
    networks:
      - app-net
volumes:
  my-db:

networks:
  app-net:

